name: Workflow Evento
on:
  workflow_dispatch:
    inputs:
      exemplo-input:
        type: string
        description: "Descrição do input exemplo"
        required: true

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "${{ inputs.exemplo-input }}"
