name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  pull_requests:
    permissions: write-all
    name: PULL REQUESTS TESTS
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=rootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout the test repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MySQL Client & Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Wait for MySQL and Initialize Database
        run: python init_db.py

      - name: Install Requirements
        run: |
          pip install -U -r requirements.txt
          npx playwright install-deps

      - name: Init Browser Library
        run: rfbrowser init

      - name: Run the tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: invoke test-pr

      - name: Validate Test Coverage
        if: always()
        id: test_coverage
        run: |
          python ./resources/libs/test_coverage_validator.py \
            ./reports/output.xml \
            --min-pass_rate 100 \
            --output-dir ./reports/pass_rate || exit 1

      - name: Read Markdown Report
        id: read_report
        if: always()
        run: |
          report_file=$(ls ./reports/pass_rate/test_pass_rate_report_*.md | head -n 1)
          echo "report_path=$report_file" >> $GITHUB_OUTPUT
          cat $report_file

      - name: Create GitHub Comment
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const reportPath = '${{ steps.read_report.outputs.report_path }}';
            const reportContent = fs.readFileSync(reportPath, 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reportContent
            });

      - name: Upload PR Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-test-results
          path: |
            ./reports
            ./reports/coverage
            ./reports/robotmetrics
          retention-days: 5
          if-no-files-found: ignore
