name: Regression Testing and Deployment

on:
  push:
    branches: 
      - main

jobs:
  regression:
    permissions: write-all
    name: Regression
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the test repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          npx playwright install-deps

      - name: Init Browser Library 
        run: rfbrowser init

      - name: Run the tests
        run: invoke test-regression
      
      - name: Metrics
        if: always()
        run: robotmetrics --input reports/ --output output.xml --metrics-report-name index.html
    
      - name: Upload Test Results Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./reports
          retention-days: 3
          if-no-files-found: ignore
  
  deploy:
    needs: regression
    runs-on: ubuntu-latest
    permissions:
      pages: write     
      id-token: write  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download report
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: ./reports/robotmetrics

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
          path: './reports/robotmetrics'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}

